#!/user/bin/bash


# --------------------------------------------------------------------------------------------------------------
#change color to blue before printing
# Color variables
BOLD="\033[1m"
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
magenta='\033[0;35m'
cyan='\033[0;36m'
# Clear the color after that
clear='\033[0m'
# Background Color variables
bg_red='\033[0;41m'
bg_green='\033[0;42m'
bg_yellow='\033[0;43m'
bg_blue='\033[0;44m'
bg_magenta='\033[0;45m'
bg_cyan='\033[0;46m'
# --------------------------------------------------------------------------------------------------------------
<<comment
---------------------------
Fonts:_
---------------------------
banner
big
block
bubble
digital
ivrit
lean
mini
mnemonic
script
shadow
slant
small
smscript
smshadow
smslant
standard
term
comment


{
for ((i=0 ; i<=100 ; i+=5));
do 
    sleep 0.1
    echo $i

done
} | whiptail  --gauge "Loading ZeroXDBMS-Script !" 6 50 0

echo "                                                                                                                       "
echo -e "${blue}--------------------------------------------------------------------------------------------------------------------------------------${clear}"
echo -e "${blue}--------------------------------------------------------------------------------------------------------------------------------------${clear}"
figlet -ctf small "ZeroX DBMS"
echo -e "${blue}--------------------------------------------------------------------------------------------------------------------------------------${clear}"
echo -e "${blue}--------------------------------------------------------------------------------------------------------------------------------------${clear}"
echo -e "                                                                                                    ${yellow}Project by : HG&AE${clear}"
