#!/user/bin/bash
#change color to blue before printing
# Color variables
BOLD="\033[1m"
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
magenta='\033[0;35m'
cyan='\033[0;36m'
# Clear the color after that
clear='\033[0m'
# Background Color variables
bg_red='\033[0;41m'
bg_green='\033[0;42m'
bg_yellow='\033[0;43m'
bg_blue='\033[0;44m'
bg_magenta='\033[0;45m'
bg_cyan='\033[0;46m'

#------------------------------------------------------------------------------------------------
#Drop_Function 
#------------------------------------------------------------------------------------------------
Check_Before_Drop_Table() {
    shopt -s extglob 
    echo -e "${red} Are You Sure You Want To Drop {$1} Table (y/n) :${clear}"
    read 
    case $REPLY in 
        [yY] ) 
            rm "$1.data"
            rm "$1.meta"
            echo -e "${green} -- Table Droped Successfully -- \n${clear}"
            select_from_connect_options
        ;;
        [Nn] )
            echo -e "${yellow}*Droped Step Canceled ${clear}"
            select_from_connect_options
        ;;
        * )
            echo -e "${red}*Wrong Entery${clear}"
            Check_Before_Drop_Table
    esac
}
#------------------------------------------------------------------------------------------------
#Drop_Function 
#------------------------------------------------------------------------------------------------
Drop_Table_Func() {
    if [[ $1 = "exit" ]];then
        select_from_connect_options
    elif [[  $1 == "" ]]; then 
        echo -e "${red}[ Error ] --- Can't Read Value You Entered --- ${clear}"
        Back_To_Menu
    elif [[ `ls | grep -i "^$1.data$"` == "" && `ls | grep -i "^$1.meta$"` == ""  ]];then
        echo -e "${red}\n[ Error ] --- Table Name Not Exist --- \n${clear}" 
        Back_To_Menu  
    else 
        echo -e "${green}\n*----------------- * Drop Table * -----------------*\n${clear}"
        Check_Before_Drop_Table $1
    fi
}
#------------------------------------------------------------------------------------------------
#Back_To_Menu_Function 
#------------------------------------------------------------------------------------------------
Back_To_Menu () {
    echo -e "1- Insert Table Name Again\n2- Cancel"
    read menu
    if [[ $menu = 1 ]];then
        echo -e "${green}Insert Table Menu${clear}"
        read -p "Enter Table Name : " D_Table
        Drop_Table_Func $D_Table 
    elif [[ $menu = 2 ]];then 
        echo -e "${green}Cancel${clear}"
        select_from_connect_options
    else 
        echo -e "${red}[ Error ] --- Enter Valid Number Please --- ${clear}" 
        Back_To_Menu
    fi
}

#------------------------------------------------------------------------------------------------
#Calling
#------------------------------------------------------------------------------------------------

read -p "Enter Table Name : " D_Table
Drop_Table_Func $D_Table


